"""
Centralized prompts module for ReTexture backend.
All AI prompts are stored here to avoid hardcoding.
"""

from .compliance_prompts import (
    COMPLIANCE_SYSTEM_PROMPT,
    SYSTEM_PROMPT,
)
from .generation_prompts import (
    TESCO_COMPLIANCE_SUFFIX,
    STYLE_STUDIO_PROMPT,
    STYLE_LIFESTYLE_PROMPT,
    STYLE_CREATIVE_PROMPT,
    STYLE_SEASONAL_PROMPT,
    get_background_generation_prompt,
)
from .headline_prompts import (
    TESCO_BRAND_GUIDELINES,
    KEYWORD_SUGGESTION_PROMPT,
    HEADLINE_GENERATION_PROMPT,
    SUBHEADING_GENERATION_PROMPT,
    TEXT_PLACEMENT_ANALYSIS_PROMPT,
    TYPOGRAPHY_STYLING_PROMPT,
)
from .validation_prompts import (
    AUTO_FIX_SYSTEM_PROMPT,
    CONTENT_GENERATION_SUBHEADLINE_PROMPT,
    CONTENT_GENERATION_HEADLINE_PROMPT,
    CONTENT_GENERATION_FALLBACK_PROMPT,
)

__all__ = [
    # Compliance
    "COMPLIANCE_SYSTEM_PROMPT",
    "SYSTEM_PROMPT",
    # Generation
    "TESCO_COMPLIANCE_SUFFIX",
    "STYLE_STUDIO_PROMPT",
    "STYLE_LIFESTYLE_PROMPT",
    "STYLE_CREATIVE_PROMPT",
    "STYLE_SEASONAL_PROMPT",
    "get_background_generation_prompt",
    # Headlines
    "TESCO_BRAND_GUIDELINES",
    "KEYWORD_SUGGESTION_PROMPT",
    "HEADLINE_GENERATION_PROMPT",
    "SUBHEADING_GENERATION_PROMPT",
    "TEXT_PLACEMENT_ANALYSIS_PROMPT",
    "TYPOGRAPHY_STYLING_PROMPT",
    # Validation
    "AUTO_FIX_SYSTEM_PROMPT",
    "CONTENT_GENERATION_SUBHEADLINE_PROMPT",
    "CONTENT_GENERATION_HEADLINE_PROMPT",
    "CONTENT_GENERATION_FALLBACK_PROMPT",
]
